language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_install:
  - sh -e .travis/scripts/apt-get.sh
  - sh -e .travis/scripts/apache2-vhost.sh
  - sh -e .travis/scripts/apache2-configure.sh

before_script:
  - composer update

script:
  - phpunit --configuration phpunit.travis.xml
